-- ============================================================
-- Apartment Management System — Database Schema
-- (Tenant Dashboard subset)
-- ============================================================

CREATE DATABASE IF NOT EXISTS apartment_management
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE apartment_management;

-- ---------------------------------------------------------
-- Tenants
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS tenants (
    tenant_id       INT AUTO_INCREMENT PRIMARY KEY,
    full_name       VARCHAR(120)  NOT NULL,
    email           VARCHAR(150)  NOT NULL UNIQUE,
    password_hash   VARCHAR(255)  NOT NULL,
    apartment_no    VARCHAR(20)   NOT NULL,
    phone           VARCHAR(30)   DEFAULT NULL,
    move_in_date    DATE          NOT NULL,
    avatar_url      VARCHAR(255)  DEFAULT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Landlords / Admins
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS landlords (
    landlord_id     INT AUTO_INCREMENT PRIMARY KEY,
    full_name       VARCHAR(120)  NOT NULL,
    email           VARCHAR(150)  NOT NULL UNIQUE,
    password_hash   VARCHAR(255)  NOT NULL,
    phone           VARCHAR(30)   DEFAULT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Monthly Bills
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS bills (
    bill_id         INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id       INT NOT NULL,
    bill_month      TINYINT NOT NULL,      -- 1-12
    bill_year       SMALLINT NOT NULL,
    apartment_rent  DECIMAL(10,2) NOT NULL DEFAULT 0,
    electricity_bill DECIMAL(10,2) NOT NULL DEFAULT 0,
    water_bill      DECIMAL(10,2) NOT NULL DEFAULT 0,
    gas_bill        DECIMAL(10,2) NOT NULL DEFAULT 0,
    service_fee     DECIMAL(10,2) NOT NULL DEFAULT 0,   -- consolidated guard/lift/trash
    status          ENUM('paid','unpaid') NOT NULL DEFAULT 'unpaid',
    paid_at         TIMESTAMP NULL DEFAULT NULL,
    due_date        DATE NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_tenant_month (tenant_id, bill_month, bill_year),
    CONSTRAINT fk_bills_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenants(tenant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Reported Issues
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS issues (
    issue_id        INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id       INT NOT NULL,
    category        ENUM('Plumbing','Electrical','Structural','Other') NOT NULL,
    description     TEXT NOT NULL,
    status          ENUM('pending','in_progress','resolved') NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_issues_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenants(tenant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Move-out Notices
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS notices (
    notice_id       INT AUTO_INCREMENT PRIMARY KEY,
    tenant_id       INT NOT NULL,
    move_out_date   DATE NOT NULL,
    reason          VARCHAR(500) DEFAULT NULL,
    status          ENUM('submitted','acknowledged') NOT NULL DEFAULT 'submitted',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notices_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenants(tenant_id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ---------------------------------------------------------
-- Seed data (demo tenant + 4 months of bills)
-- ---------------------------------------------------------
INSERT INTO tenants (full_name, email, password_hash, apartment_no, phone, move_in_date)
VALUES ('Ariana Karim', 'ariana.karim@example.com', '$2y$10$demoDemoDemoDemoDemoOuHash', 'B-402', '+880 1711-223344', '2023-03-01')
ON DUPLICATE KEY UPDATE full_name = VALUES(full_name);

-- NOTE: the password_hash values above/below are placeholders, not real
-- bcrypt hashes. Real hashes are generated by auth.php's Sign Up form via
-- PHP's password_hash() the first time someone registers for real.
INSERT INTO landlords (full_name, email, password_hash, phone)
VALUES ('Rafiq Hasan', 'rafiq.hasan@example.com', '$2y$10$demoDemoDemoDemoDemoOuHash', '+880 1811-556677')
ON DUPLICATE KEY UPDATE full_name = VALUES(full_name);

-- tenant_id assumed to be 1 for the seed rows below
INSERT INTO bills (tenant_id, bill_month, bill_year, apartment_rent, electricity_bill, water_bill, gas_bill, service_fee, status, due_date, paid_at) VALUES
(1, 7, 2026, 15000.00, 1850.00, 600.00, 450.00, 1200.00, 'unpaid', '2026-07-10', NULL),
(1, 6, 2026, 15000.00, 2100.00, 620.00, 470.00, 1200.00, 'paid',   '2026-06-10', '2026-06-08 14:22:00'),
(1, 5, 2026, 15000.00, 1720.00, 580.00, 430.00, 1200.00, 'paid',   '2026-05-10', '2026-05-09 10:05:00'),
(1, 4, 2026, 14500.00, 1990.00, 610.00, 460.00, 1200.00, 'paid',   '2026-04-10', '2026-04-07 09:40:00')
ON DUPLICATE KEY UPDATE status = VALUES(status);
